### PR TITLE
Update camera.lua

### LINKED ISSUE #69: Canvas fails to render when camera attached
Hello,

I'm running into an issue where within a block of camera attach/detach calls, a canvas fails to render correctly. I'm hoping you can help indicate the issue with my test code or verify that this is a bug with  the expected behavior of hump.camera:

```lua
local attachcam = true -- set to false to see expected behavior
local camera = require('hump.camera')(0,0)
local canvasWithCam = love.graphics.newCanvas(50, 50)
local canvasWithoutCam = love.graphics.newCanvas(50, 50)

function love.draw()        
    -- Works as expected
    love.graphics.setCanvas(canvasWithoutCam)    
    love.graphics.rectangle('fill', 0, 0, 50, 50)    
    love.graphics.setCanvas()  
    love.graphics.draw(canvasWithoutCam, 0, 0)
    
    -- if cam is attached, canvas fails to render
    if attachcam then camera:attach() end
    love.graphics.setCanvas(canvasWithCam)    
    love.graphics.rectangle('fill', 0, 0, 50, 50)    
    love.graphics.setCanvas()  
    love.graphics.draw(canvasWithCam, 100, 0)
    if attachcam then camera:detach() end
end
```

I do not have any viable workaround at this time, but if I develop one I will post my updated code. Thanks for your time! Please let me know if you need any further details.

### PR DESCRIPTION
**Pull request by buckle2000**
Fixed #69

### CODE REVIEW

**Comment by palmettos** [comment]
This code contains errors in your [commit](https://github.com/vrld/hump/pull/70/commits/311740996ea5144b278e705e90f046588dbe2791):
```
function camera:attach(clip)
 	-- clip   nil or {x, y, w, h}
 	self.clip = clip
 	if clip then
 		self.clip = true
 		x,y = x or 0, y or 0
 		w,h = w or love.graphics.getWidth(), h or love.graphics.getHeight()
 
 		self._sx,self._sy,self._sw,self._sh = love.graphics.getScissor()
 		love.graphics.setScissor(unpack(clip))
```

This fix works as you intended:
```
function camera:attach(x, y, w, h, clip)
	-- clip   nil or {x, y, w, h}

	x, y = x or 0, y or 0
	w, h = w or love.graphics.getWidth(), h or love.graphics.getHeight()

	self.clip = clip
	if clip then
		self.clip = true
		self._sx,self._sy,self._sw,self._sh = love.graphics.getScissor()
		love.graphics.setScissor(unpack(clip))
```

**Comment by buckle2000** [comment]
Oh, I made a capatibility-breaking change because there is no good to set scissor to current screen since it is set by default.
You can use this if you want:
https://github.com/vrld/hump/pull/70/commits/fcb0e87d4e4231e34571ed152eed57e5b9c8a662

**Comment by palmettos** [comment]
I understand your reasoning. I'm saying your code does not work. It breaks ``camera.attach`` because ``x, y, w, h`` are not defined in its arguments and are also nested in the conditional, which will leave them undefined in the outer scope of the function if ``self.clip`` is ``nil``.

**Comment by buckle2000** [comment]
Thank you for your feedback! Now it should work.

**Comment by palmettos** [comment]
Nice!

**Comment by palmettos** [comment]
I just noticed your latest change breaks ``camera.draw``, which uses the ``camera.attach(x, y, w, h, noclip)`` signature.

**Comment by palmettos** [comment]
I just noticed your latest change breaks ``camera.draw`` because it uses the ``camera.attach(x, y, w, h, noclip)`` signature.

**Comment by buckle2000** [comment]
Thank you!

**Comment by buckle2000** [comment]
Also fixed #71 .

**Comment by buckle2000** [comment]
@vrld hello?

**Comment by vrld** [comment]
This does not really FIx #69 (see comment there), but changes the behavior of `hump.camera`. Also, the functions `draw()` and `attach()` now have different signatures (one uses a table argument, the other uses varargs). So I will not merge this pull request.

But if you can create a new pull request with your changes to `hump.class` and the gamestate docs I am happy to merge it!

**Pull request closed without merging**
