### PR TITLE
Fixed #77 - Allow registering functions to signal patterns

### LINKED ISSUE #77: Enhancement: register a function to every signal
I'd like to be able to register a function that will be called with every 'emit'. I'd use that to call 'print' with every signal to have a log of events. e.g:
```lua
Signal.register(function(...) print("signal emmited", ...) end)
```

### PR DESCRIPTION
**Pull request by palmettos**

### CODE REVIEW

**Comment by premek** [comment]
but this will register only to **previously registered** signals, right?
It would be better if you can register it for any pattern that may be registered later or never.

**Comment by palmettos** [comment]
That is true, but the only way to make it work the way you suggest is to add a layer of linear time complexity on top of the existing code which is mostly O(1)... and I'm not sure if @vrld  would want that.

**Comment by palmettos** [comment]
Just thinking about the problem for a few minutes, the solution really doesn't fit into the existing code well at all. It would probably be better to simply wrap `Registry.emit` in your own code to achieve the functionality you're looking for.

**Comment by vrld** [comment]
Looks good. I'll merge now and add documentation later (unless you want to ;)

**Pull request merged**
