### PR TITLE
feat(vector): Export dist, dist2 functions, added :distTo, :dist2To

### PR DESCRIPTION
**Pull request by shousper**

### CODE REVIEW

**Comment by vrld** [comment]
But why?

**Comment by shousper** [comment]
Because they're not exported or used, but are useful :) Saves importing vector-light as well.

**Comment by vrld** [comment]
These functions are part of the [metatable](https://github.com/vrld/hump/blob/master/vector.lua#L34):

    a = vector(1,0)
    print(a:dist(vector.zero)) -- 1

See also [here](http://hump.readthedocs.io/en/latest/vector.html#vector:dist).

**Comment by shousper** [comment]
Ooo, indeed, thank you! It appears I've been spoilt by the object syntax of an OOP lib I've been using.

I think I also got confused when I spotted the code for the `len` and `dist`functions were duplicated. Can I ask, is this a little micro optimisation?

Thanks for your time @vrld

**Comment by vrld** [comment]
Yes, `(a-b):len()` would create a table, which would immediately be discarded. Here is some code to test the performance difference (the code uses [online calculation of mean an varinance](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Online_algorithm)):

```lua
local vector = require 'vector'

local function timeit(iter_outer, iter_inner, f)
  local mean, variance = 0, 0
  for outer = 1, iter_outer do
    local now = os.clock()
    for inner = 1, iter_inner do
      f()
    end

    local dt = os.clock() - now
    local dm = dt - mean
    mean = mean + dm / outer
    variance = variance + dm * (dt - mean)
  end

  variance = variance / (iter_outer - 1)
  print(("time: %.2f +- %.2f ms"):format(mean*1000, math.sqrt(variance)*1000))
end

print("(a-b):len()")
timeit(1000, 2000, function()
  return (vector.randomDirection() - vector.randomDirection()):len()
end)

print("a:dist(b)")
timeit(1000, 2000, function()
  return vector.randomDirection():dist(vector.randomDirection())
end
```

On my machine, the effect is small, but still there. With lua, `dist()` is about 12% faster:

    (a-b):len()
    time: 6.21 +- 0.32 ms
    a:dist(b)
    time: 5.50 +- 0.29 ms

luajit apparently optimizes out the temporary table, so there is no significant difference between the two:

    (a-b):len()
    time: 0.19 +- 0.06 ms
    a:dist(b)
    time: 0.17 +- 0.02 ms

**Pull request closed without merging**
